// export const ssr = false;
import Head from "next/head";
import Script from "next/script";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConditionalMainHead } from "@/components/ConditionalMainHead";
import { I18nProvider } from "@/components/I18nProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "React Native & Expo",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/favicon.ico", sizes: "any" },
            { url: "/favicon.ico", sizes: "32x32", type: "image/x-icon" },
            { url: "/favicon.ico", sizes: "16x16", type: "image/x-icon" },
        ],
        shortcut: "/favicon.ico",
        apple: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <link rel="icon" href="/favicon.ico" type="image/x-icon" />
                <link rel="shortcut icon" href="/favicon.ico" />
                <meta name="theme-color" content="#000000" />
                {/* Google Analytics */}
                <Script src="https://www.googletagmanager.com/gtag/js?id=G-PFV33EY4NK" strategy="afterInteractive" />
                <Script id="google-analytics" strategy="afterInteractive">
                    {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-PFV33EY4NK');
          `}
                </Script>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-full bg-gradient-to-br from-gray-50 to-gray-100`}>
                <I18nProvider>
                    <ConditionalMainHead />
                    {children}
                    {/* <SplashCursor /> */}
                </I18nProvider>
            </body>
        </html>
    );
}
export const dynamic = "force-dynamic";
